//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaGith.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquiler
    {
        public int Id { get; set; }
        public Nullable<int> Id_Socio { get; set; }
        public Nullable<int> Id_Libro { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Libros Libros { get; set; }
        public virtual Socios Socios { get; set; }
    }
}
